### ISSUE TITLE
notoserif-regular-subset.ttf not found

### ISSUE THREAD

**Issue by blling** [asciidoctor/asciidoctor-maven-examples#106]
How to resolve this problem?
```
Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:2.1.0:process-asciidoc (generate-pdf-cjk-zh_CN-doc) on project pnr-push-docs: Execution generate-pdf-cjk-zh_CN-doc of goal org.asciidoctor:asciidoctor-maven-plugin:2.1.0:process-asciidoc failed: org.jruby.exceptions.SystemCallError: (ENOENT) No such file or directory - notoserif-regular-subset.ttf not found in /xxxxxxxxxxxxxxx/yyyyyyyyyyyyyyyyyyy/zzzzzzzzzzzzzzzzzzzzzz
```

**Comment by mojavelinux** [comment]
Are you using https://github.com/chloerei/asciidoctor-pdf-cjk by chance? If so, that is no longer compatible with Asciidoctor PDF. It's best to follow these instructions instead: https://github.com/asciidoctor/asciidoctor-pdf#create-a-custom-cjk-theme

**Comment by abelsromero** [comment]
> It's best to follow these instructions instead: https://github.com/asciidoctor/asciidoctor-pdf#create-a-custom-cjk-theme

That's what the maven example does under the hood, it no longer uses the gem. Though the theme has not been updated in a while and still uses `font_family` instead of `font-family`. Could that cause issues?

Btw, sorry to say I could not reproduce in my Linux machine, even renaming the path of noto fonts. Also the CN PDF generated does not contain Noto in the table of fonts.

**Comment by mojavelinux** [comment]
> uses font_family instead of font-family. Could that cause issues?

It should not. The keys are interchangeable.

**Comment by blling** [comment]
I use https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-pdf-cjk-example, and config `<pdf-style>` to a wrong value, so i get the error, now it is **OK** after i use the correct config.

A suggestion, should `asciidoctor-pdf-cjk-example` be update to not use chloerei/asciidoctor-pdf-cjk, since ` it is no longer compatible with Asciidoctor PDF`?
```xml
        <pdf.cjk.kaigen.version>0.1.1</pdf.cjk.kaigen.version>
        <pdf.cjk.kaigen.fonts.download.uri>https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/releases/download/v0.1.0-fonts</pdf.cjk.kaigen.fonts.download.uri>
        <pdf.cjk.kaigen.themes.download.uri>https://raw.githubusercontent.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic/master/data/themes</pdf.cjk.kaigen.themes.download.uri>
        <pdf.cjk.kaigen.download.dir>${project.build.directory}/downloaded-resources</pdf.cjk.kaigen.download.dir>
```

**Comment by abelsromero** [comment]
> now it is **OK**

🎉 

> A suggestion, should `asciidoctor-pdf-cjk-example` be update to not use chloerei/asciidoctor-pdf-cjk, since ` it is no longer compatible with Asciidoctor PDF`?

It is already working according to the manual, but maybe the details are too hidden for what aims to be an ilustrative example. We could include a theme in the same project so is more obvious to users. Or review the note in the readme https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoctor-pdf-cjk-example/README.adoc#usage. **wdyt makes things more clear ?**

Right now, instead of using a custom theme in the same project we download the default from chloerei's https://github.com/asciidoctor/asciidoctor-maven-examples/blob/16f375d0aa24828c524bbce22d3f436c18b44d93/asciidoctor-pdf-cjk-example/pom.xml#L38-L49 into https://github.com/asciidoctor/asciidoctor-maven-examples/blob/16f375d0aa24828c524bbce22d3f436c18b44d93/asciidoctor-pdf-cjk-example/pom.xml#L26, and then use it in the build https://github.com/asciidoctor/asciidoctor-maven-examples/blob/16f375d0aa24828c524bbce22d3f436c18b44d93/asciidoctor-pdf-cjk-example/pom.xml#L283-L284.

For constrast, the old (now unsupported) usage, integrated the code as a Ruby extension https://github.com/chloerei/asciidoctor-pdf-cjk/tree/master/lib.

**Comment by blling** [comment]
@mojavelinux @abelsromero Thanks for all your details, i got it now. `asciidoctor-pdf` help me a lot, thanks for your great work again. :-)
