### ISSUE TITLE
Update example to use newer asciidoctor-diagram version supporting imagesoutdir setting.

### ISSUE THREAD

**Issue by yeroc** [asciidoctor/asciidoctor-maven-examples#27]
It would be nice to update the `asciidoctor-diagram-example` to use the newer asciidoctor-diagram v1.3.0 release (once it is released, currently in preview) and then update the pom to specify the new `imagesoutdir` property so that generated graphs don't end up mixed in the `src` directory.

**Comment by yeroc** [comment]
See https://github.com/asciidoctor/asciidoctor-diagram/issues/59 for further details.

**Comment by abelsromero** [comment]
Thanks for the tip, keeping track of all dependecies is hard.
Btw, I tested it and it works nicely just updating the version, no need to add the extra `imagesoutdir` parameter. Will you then, send the Pull Request? :wink:

And, If you can...can you also tip/PR the guys at [asciidoctorj](https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-diagram/gradle.properties/)? asciidoctor-diagram is embedded into asciidoctorj and seems to be using an old version too.

Once they update and publish, we can update this example to use the embedded version in the same way as in the [pdf example](https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoctor-pdf-example/pom.xml)...meanwhile we'll have to wait and open and _traking_ issue.

@mojavelinux Since this example uses the old way to integrate gems, if we update this, we will need another sub-project to show how to integrate ruby extensions, any nice extension you can think off?

**Comment by mojavelinux** [comment]
> I tested it and it works nicely just updating the version, no need to add the extra imagesoutdir parameter.

That's right! When the change was made to add imagesoutdir, the default behavior was also changed to put the images into the destination directory instead of the source directory. The imagesoutdir is only needed if you want to change that new default.

>  asciidoctor-diagram is embedded into asciidoctorj 

Actually, that's not official yet. It won't be available until the 1.5.3 release at the earliest.

> we will need another sub-project to show how to integrate ruby extensions, any nice extension you can think off?

Absolutely. An obvious choice is Asciidoctor LaTeX (https://github.com/asciidoctor/asciidoctor-latex). Of course, that could eventually get rolled into AsciidoctorJ, so then I might suggest asciidoctor-html5ruby or asciidoctor-diagram-cacoo.

**Comment by jmini** [comment]
With #35 I have updated `asciidoctor-diagram` to 1.3.1.

Switching to `asciidoctorj-diagram` instead of `asciidoctor-diagram` is tracked in #12

I do not think that we need to set `imagesoutdir` to something else, because now the images are no longer generated in source folder. See this comment from @mojavelinux:
> … the default behavior was also changed to put the images into the destination directory instead of the source directory. The imagesoutdir is only needed if you want to change that new default.

The last comment about having a maven example to demonstrate how ruby gems can be used is important, but I suggest we track this somewhere else.

I my opinion this issue can be closed.

**Comment by mojavelinux** [comment]
:+1:
