### ISSUE TITLE
Maven site "theme" does not look like PDF theme

### ISSUE THREAD

**Issue by sikron** [asciidoctor/asciidoctor-maven-examples#31]
Hi,
i want to use asciidoc for both my maven-site and a generated PDF. I followed both your 'asciidoc-maven-site-example' and 'asciidoctor-pdf-example' with no alterations.

The generated PDF looks really great, but the maven-site does not look like the PDF at all, e.g.
- the source-code is not formatted as source-code, only verbatim and without background
- table borders are invisible, cells do not have any background

Is this by intention? Can i customize this by myself - preferrable without editing the css, but e.g. by attributes in the pom.xml?

I added pictures for better understanding. this is the poor-looking maven-site:
![maven-site](https://cloud.githubusercontent.com/assets/2979076/9256779/c95012fa-41f1-11e5-94bd-34bcf1c0bddf.png)

and this is the great-looking PDF:
![pdf](https://cloud.githubusercontent.com/assets/2979076/9256816/2a9347ee-41f2-11e5-9c95-4abd45bc4de3.png)

**Comment by sikron** [comment]
ok, i am answering my own question: 
in order to have good source-highlighting, etc, the asciidoctor-maven-plugin in version 1.5.2.1 is needed (i had 1.5.2)

**Comment by abelsromero** [comment]
Glad you could found a solution.
Feel free to close the issue when you want :)

**Comment by sikron** [comment]
i am not 100% happy content with the theming actually, but right now it suffices, i think.
thanks!

**Comment by abelsromero** [comment]
> i am not 100% happy with the theming actually, but right now it suffices, i think.

Please, let us know if there's anything that can be improved.

**Comment by sikron** [comment]
Hi again, 
thanks for offering your help! :-)
Actually, i think, there is a problem with tables. I have made a dummy-maven-project for comparing the output of the HTML for tables with the plain maven-site-plugin and apt-format vs. the maven-site plugin with asciidoctor-maven-plugin 1.5.2.1. Comparing the table, the output for the plain apt generates a table with borders and alternating line-background-colors as expected. The output of the asciidoc-plugin generates a table without borders and background-colors.
Is this by intention? How can i let the asciidoc-table have borders and colors?

The html-output of apt is a `<table border="1" class="bodyTable">`, whereas for asciidoc it is `<table class="tableblock frame-all grid-all spread">`. I haven't found any of the asciidoc-table-classes in the generated css-files. are they missing or are they some standard-css-classes?

here a picture with the apt-table at the top and the asciidoc-table below.
![tables](https://cloud.githubusercontent.com/assets/2979076/9294420/76739454-444d-11e5-8f8e-ee047a45483d.png)

many thanks!

**Comment by abelsromero** [comment]
> I have made a dummy-maven-project

Can you share that project? It will help me a lot to look into the issue.

Also if you feel like hacking a bit yourself :wink: you can have a look at the code (https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/master/src/main/java/org/asciidoctor/maven/site/AsciidoctorParser.java#L52).
Basically, what the maven-plugin does is render/convert the documents (intro a String) with some pre-set options and then embed the result into the `site` page.

Two options come to my mind that need testing:
1. **Add a role to your tables** (http://asciidoctor.org/docs/user-manual/#role). Knowing that you need the class `bodyTable`, you could add that role to the table like this.

```
[role="bodyTable"]
|===
|languange|1|2

|english
|one
|two

|catalan
|u
|dos

|===
```
This created the next table block `<table class="tableblock frame-all grid-all spread bodyTable">`. Maybe this is enough?
2 . Some **string replacement** in the [plugin](https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/master/src/main/java/org/asciidoctor/maven/site/AsciidoctorParser.java#L52).

Personally, I don't like the second options because it's susceptible for changes in the asciidoctor generation format. And even if you plan to use the document in different backends, you coud add some conditional block to add the rol only under some conditions (check http://discuss.asciidoctor.org/Conditional-inclusion-td2568.html).
```
ifdef::site[]
[role="bodyTable"]
endif::[]
```

Btw, I'll move this issue to the [maven plugin](https://github.com/asciidoctor/asciidoctor-maven-plugin/) tomorrow. Today I'm not at home.

**Comment by abelsromero** [comment]
This issue was moved to asciidoctor/asciidoctor-maven-plugin#166
