### ISSUE TITLE
Missing minimal asciidoctor-diagram maven project

### ISSUE THREAD

**Issue by krzyk** [asciidoctor/asciidoctor-maven-examples#34]
Current maven project with diagrams adds a lot of configuration that I don't think is necessary (e.g. specifying jruby version - user shouldn't care about that).

Please create an example that uses existing graphviz/dot maven packages and not connect to repository other than maven central (some companies have maven mirrors that download only from central).

**Comment by abelsromero** [comment]
Hi,

I agree that some configuration is not required, but the examples are meant to ilustrate different scenarios and help with common pitfalls. In that sense, I think that the current examples are aligned to those principles and unnessary sections are documented in the main README and the pom.xml itself. Of couse, documentation can be improved, if you see any confusing section please ponit it directly.

> uses existing graphviz/dot maven packages and not connect to repository other than maven central

Can you offer more info? _The summary_ is that I'm not aware of such package and since extensions are written in Ruby you need to download the gems (gems are jars for ruby) from a Ruby repository. Also, in the end some graphs require that you install the `dot` command separately and set your local PATH, so, getting a 100% solo maven example is not possible. :disappointed:

_The long story_ is that we are aware of both this issues, to fix the first one (gem download) the most common ruby extensions are being budled as jars with [asciidoctorj](https://github.com/asciidoctor/asciidoctorj/tree/master/asciidoctorj-diagram). The current snapshot version of asciidoctorj already includes the diagram, so in 1.5.3 we will update the example to reflect that. The second issue though (installing dot) is not easy since it is not a matter of wrapping a component as a jar, on other words, no fix for that.

**Comment by mojavelinux** [comment]
> The current snapshot version of asciidoctorj already includes the diagram, so in 1.5.3 we will update the example to reflect that. 

AsciidoctorJ Diagram is now available (1.3.1). See http://search.maven.org/#artifactdetails%7Corg.asciidoctor%7Casciidoctorj-diagram%7C1.3.1%7Cjar

**Comment by jmini** [comment]
This will be solved with #12
