### ISSUE TITLE
Make the module names and Maven project names consistent

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor-maven-examples#7]
Current, the following module names are used:

````
<modules>
        <module>asciidoc-multiple-inputs-example</module>
        <module>asciidoc-site-example</module>
        <module>asciidoc-to-html-example</module>
        <module>asciidoc-to-pdf-example</module>
        <module>asciidoctor-diagram-example</module>
        <module>docbook-pipeline-docbkx-example</module>
        <module>docbook-pipeline-jdocbook-example</module>
    </modules>
````

So most of them start with `asciidoc`, except `asciidoctor-diagram-example`. I would propose to rename that one to `asciidoc-diagram-example`

The `asciidoc-to-pdf-example` module uses `asciidoctor-pdf-example` as artifact id. I would propose to change the artifact id to `asciidoc-to-pdf-example`

If you are ok with these changes, I can create a pull request for them.

**Comment by mojavelinux** [comment]
I do agree the module name and artifact id should match.

The reason we use the name `asciidoctor-diagram-example` is because it demonstrates the use of `asciidoctor-diagram` specifically. I'd like the module name to indicate which technology it's demonstrating, so I think the `asciidoc-to-pdf-example` should actually be named `asciidoctor-pdf-example`. So I'm proposing the inverse of what your proposing.

**Comment by wimdeblauwe** [comment]
Ok, so to summarize:

* Rename module directory `ascii-doc-to-pdf-example` to `asciidoctor-pdf-example`
* Rename `asciidoc-site-example` to `asciidoctor-site-example` (Module and artifactId)
* Rename `asciidoc-to-html-example` to `asciidoctor-html-example` (Module and artifactId)

Ok?

**Comment by mojavelinux** [comment]
Yes to the first bullet.

The second bullet is actually AsciiDoc in a Maven Site, so we aren't really emphasizing Asciidoctor here (per se). I either like it unchanged or as `asciidoc-maven-site-example` or `maven-site-asciidoc-example`.

The last one is only demonstrating AsciiDoc to HTML, so technically it's correct as is. I specifically named it that way since I know people will likely be looking for that specific use case when just starting out.

I realize there's no clear right answer here, but I think that with the change to (1) and proposed change to (2), it works out pretty nicely.

**Comment by wimdeblauwe** [comment]
Ok. This is the pull request I have created to match what you ask: https://github.com/asciidoctor/asciidoctor-maven-examples/pull/9

**Comment by abelsromero** [comment]
I don't mean to extend this and I'm not strongly for either `-to-pdf` or just `pdf`. However, since the integration of asciidcotor-pdf in asciidoctorj, the html and pdf examples show basically the same maven configuration.
Previously the pdf example naming did make sense because it showed how to add an addition ruby gem, but now it's just a standard backend configuration. Does it make sense to rename it?

**Comment by mojavelinux** [comment]
I think in this case yes because it's still a contrast from the docbook pipelines. This helps people understand that there are multiple paths to pdf (in other words, there isn't just a single pdf backend, per se).

We definitely shouldn't think too deeply about this, though, because in the end, if it makes sense to a person browsing for examples, that's what really matters. So we should keep our ears open and if we see people getting confused, we can work towards improvements in the names.

**Comment by wimdeblauwe** [comment]
I guess this issue can be resolved since it is merged?

**Comment by abelsromero** [comment]
Yup! Btw, a nice way to ease the management is used some key words that github recognizes. This way, you can link PR to issues --> https://help.github.com/articles/closing-issues-via-commit-messages/
